requires "Gtk3";
requires "Pango";
requires "Glib";
requires "Gtk3::ImageView";
requires "XML::LibXML";
requires "Net::DBus";
requires "HTTP::Status";
requires "GooCanvas2";
requires "Locale::gettext";
requires "File::Copy::Recursive";
requires "Moo", ">= 2.0";
requires "Log::Any";
requires "Log::Any::Adapter";
requires "Log::Any::Adapter::Stderr";
requires "Log::Any::Adapter::File";

test_requires "Test::MockModule";
test_requires "Test::Strict";
test_requires "Perl::Critic";
test_requires "Test::Perl::Critic";
